### ISSUE TITLE
i use nextjs for new project , when i install widget all dependecy ,i get this error Module not found: Can't resolve '@mysten/dapp-kit'

### ISSUE THREAD

**Issue by GalaxySciTech** [lifinance/widget#427]
Module not found: Can't resolve '@mysten/dapp-kit'

<img width="1072" alt="Image" src="https://github.com/user-attachments/assets/a176cc3d-29c4-4390-b3b5-83bb630d842c" />

**Comment by GalaxySciTech** [comment]
after i install @mysten/dapp-kit , then i get new error 

<img width="1109" alt="Image" src="https://github.com/user-attachments/assets/3fc4a9a4-293d-4210-8427-a228d5b237ef" />

**Comment by GalaxySciTech** [comment]
waster my a lot time for facing this , still cant success integrate widget now

**Comment by GalaxySciTech** [comment]
u can use `npx create-next-app@latest` to try and run `yarn add @lifi/widget wagmi @bigmi/react @solana/wallet-adapter-react @tanstack/react-query` to try 


```
{
  "name": "xxxx",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@bigmi/react": "^0.3.1",
    "@lifi/wallet-management": "^3.11.1",
    "@lifi/widget": "^3.23.3",
    "@mysten/dapp-kit": "^0.16.12",
    "@solana/wallet-adapter-react": "^0.15.39",
    "@tanstack/react-query": "^5.80.7",
    "next": "15.3.4",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "wagmi": "^2.15.6"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^3",
    "@tailwindcss/postcss": "^4",
    "eslint": "^9",
    "eslint-config-next": "15.3.4",
    "tailwindcss": "^4"
  }
}
```

**Comment by effie-ms** [comment]
> u can use `npx create-next-app@latest` to try and run `yarn add @lifi/widget wagmi @bigmi/react @solana/wallet-adapter-react @tanstack/react-query` to try
> by the way , my npm version is 11 , im using yarn

@ GalaxySciTech your `package.json` looks fine to me.

Following `npx create-next-app@latest` -> `yarn add @lifi/widget wagmi @bigmi/react @solana/wallet-adapter-react @tanstack/react-query`, I have managed to reproduce the first issue with Yarn (Module not found: Can't resolve '@mysten/dapp-kit'), then added `@mysten/dapp-kit` with `yarn add @mysten/dapp-kit`, and it got resolved with no other errors. I have not managed to reproduce this [error](https://github.com/lifinance/widget/issues/427#issuecomment-2985712601), could you try to remove `yarn.lock` and `node_modules` folder and run `yarn install` (to regenerate lock file and reinstall the dependencies)?

Using dependencies from your `package.json` builds and renders with no issues for me.

**Comment by GalaxySciTech** [comment]
i deleted `yarn.lock` and `node_modules` , but still have this issue , cant solve this now 

<img width="1230" alt="Image" src="https://github.com/user-attachments/assets/24999b7a-1760-4505-b172-b434a18b76ab" />


```
{
  "name": "swapbbb",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@bigmi/react": "^0.3.1",
    "@lifi/wallet-management": "^3.11.1",
    "@lifi/widget": "^3.23.3",
    "@mysten/dapp-kit": "^0.16.12",
    "@solana/wallet-adapter-react": "^0.15.39",
    "@tanstack/react-query": "^5.80.7",
    "next": "15.3.4",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "wagmi": "^2.15.6"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^3",
    "@tailwindcss/postcss": "^4",
    "eslint": "^9",
    "eslint-config-next": "15.3.4",
    "tailwindcss": "^4"
  }
}

```

**Comment by GalaxySciTech** [comment]
https://github.com/lifinance/widget/issues/427#issuecomment-2987779114
i public the repo ,here is link
[repo](https://github.com/GalaxySciTech/swapbbb)
